import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext.jsx';
import { useSubmissionLock } from '../../hooks/useSubmissionLock.js';
import { apiRequest } from '../../services/api.js';
import { alerts } from '../../utils/alerts.js';
import { dateText, EmptyRow, StatusBadge } from '../services/ServiceUi.jsx';

const API = '/api/water/admin';
const PAGE_SIZE = 15;

export const WATER_ADMIN_DOMAINS = {
  connections: { key: 'connections', detail: 'connection', statuses: ['Pending', 'Under Review', 'Approved', 'Rejected', 'Active', 'Disconnected'], fields: [['monthly_rate', 'Monthly rate', 'number'], ['admin_remarks', 'Admin remarks', 'textarea']] },
  bills: { key: 'bills', detail: 'bill', statuses: ['Pending', 'Paid', 'Failed', 'Overdue'], fields: [['admin_remarks', 'Admin remarks', 'textarea']], payment: true },
  quality: { key: 'reports', detail: 'report', statuses: ['Reported', 'Under Investigation', 'Testing', 'Action Taken', 'Resolved', 'Closed'], fields: [['test_result', 'Test result', 'textarea'], ['admin_remarks', 'Admin remarks', 'textarea']], extraFilter: ['severity', ['Low', 'Medium', 'High', 'Critical']] },
  complaints: { key: 'complaints', detail: 'complaint', statuses: ['Submitted', 'Assigned', 'In Progress', 'Resolved', 'Rejected', 'Closed'], fields: [['assigned_to', 'Assigned to'], ['resolution', 'Resolution', 'textarea'], ['admin_remarks', 'Admin remarks', 'textarea']], extraFilter: ['priority', ['Low', 'Normal', 'High', 'Emergency']] }
};

const PROJECT_TYPES = ['Flood Control', 'Irrigation', 'Drainage', 'River Dredging', 'Embankment', 'Water Treatment Plant', 'Pipeline Extension', 'Tube Well Installation', 'Sewerage', 'Desalination', 'Other'];
const PROJECT_STATUSES = ['Planned', 'Ongoing', 'Completed', 'Suspended', 'Cancelled'];
const PROJECT_FIELDS = [['project_name', 'Project name', 'text', true], ['project_name_bn', 'Bangla name'], ['project_type', 'Project type', 'type'], ['implementing_agency', 'Implementing agency'], ['division', 'Division', 'text', true], ['district', 'District'], ['budget_crore', 'Budget (crore)', 'number'], ['start_date', 'Start date', 'date'], ['expected_completion', 'Expected completion', 'date'], ['progress_percent', 'Progress percent', 'number'], ['beneficiaries', 'Beneficiaries', 'number'], ['description', 'Description', 'textarea'], ['status', 'Status', 'status']];
const SECTIONS = ['dashboard', ...Object.keys(WATER_ADMIN_DOMAINS), 'projects'];

function title(row) { return row.connection_number || row.project_name || row.complaint_type || row.issue_type || row.billing_month || `Record #${row.id}`; }

export default function AdminWaterPage() {
  const { clearAdminSession } = useAuth(); const navigate = useNavigate();
  const [params, setParams] = useSearchParams();
  const initial = SECTIONS.includes(params.get('section')) ? params.get('section') : 'dashboard';
  const [section, setSection] = useState(initial);
  const [filters, setFilters] = useState({ status: params.get('status') || '', search: params.get('search') || '', severity: params.get('severity') || '', priority: params.get('priority') || '' });
  const [stats, setStats] = useState({}); const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null);
  const [page, setPage] = useState(Math.max(1, Number(params.get('page')) || 1)); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const { submitting, runLocked } = useSubmissionLock(); const config = WATER_ADMIN_DOMAINS[section];
  const pages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE)); const current = Math.min(page, pages);
  const visible = useMemo(() => rows.slice((current - 1) * PAGE_SIZE, current * PAGE_SIZE), [rows, current]);

  function urlQuery(nextSection = section, nextFilters = filters, nextPage = 1) {
    const query = new URLSearchParams(); if (nextSection !== 'dashboard') query.set('section', nextSection);
    Object.entries(nextFilters).forEach(([key, value]) => { if (value) query.set(key, value); }); if (nextPage > 1) query.set('page', nextPage); return query;
  }
  async function loadStats() { const data = await apiRequest(`${API}/stats`, { audience: 'admin' }); setStats(data?.stats || {}); }
  async function loadRows(nextSection = section, nextFilters = filters) {
    if (nextSection === 'dashboard') return setRows([]);
    const query = new URLSearchParams(); if (nextSection !== 'projects') {
      if (nextFilters.status) query.set('status', nextFilters.status); if (nextFilters.search) query.set('search', nextFilters.search.trim());
      const extra = WATER_ADMIN_DOMAINS[nextSection]?.extraFilter?.[0]; if (extra && nextFilters[extra]) query.set(extra, nextFilters[extra]);
    }
    const data = await apiRequest(`${API}/${nextSection}${query.size ? `?${query}` : ''}`, { audience: 'admin' });
    setRows(nextSection === 'projects' ? data?.projects || [] : data?.[WATER_ADMIN_DOMAINS[nextSection].key] || []);
  }
  async function load() { setLoading(true); setError(''); try { await Promise.all([loadStats(), loadRows()]); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function choose(next) { const empty = { status: '', search: '', severity: '', priority: '' }; setSection(next); setFilters(empty); setPage(1); setSelected(null); setLoading(true); setParams(urlQuery(next, empty), { replace: true }); try { await loadRows(next, empty); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  async function filter(event) { event.preventDefault(); setLoading(true); setPage(1); setSelected(null); setParams(urlQuery(section, filters), { replace: true }); try { await loadRows(); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  function changePage(next) { setPage(next); setParams(urlQuery(section, filters, next), { replace: true }); }
  async function view(row) { setSelected({ row, loading: true }); try { const data = await apiRequest(`${API}/${section}/${row.id}`, { audience: 'admin' }); setSelected({ row, detail: data[config.detail], loading: false }); } catch (e) { setSelected(null); setError(e.message); } }
  async function update(event) { event.preventDefault(); const values = new FormData(event.currentTarget); await runLocked(async () => { const body = { status: values.get('status') }; config.fields.forEach(([name]) => { body[name] = values.get(name) || ''; }); try { const data = await apiRequest(`${API}/${section}/${selected.detail.id}`, { method: 'PUT', audience: 'admin', body }); await alerts.success('Record updated', data.message); setSelected(null); await Promise.all([loadStats(), loadRows()]); } catch (e) { setError(e.message); await alerts.error(e.message); } }); }
  async function editProject(row) { setSelected({ project: true, loading: true, row }); try { const data = await apiRequest(`${API}/projects/${row.id}`, { audience: 'admin' }); setSelected({ project: true, detail: data.project, row, loading: false }); } catch (e) { setError(e.message); setSelected(null); } }
  async function saveProject(event) { event.preventDefault(); const values = new FormData(event.currentTarget); await runLocked(async () => { const body = {}; PROJECT_FIELDS.forEach(([name]) => { body[name] = values.get(name) || ''; }); body.is_active = values.get('is_active') === '0' ? 0 : 1; const editing = Boolean(selected.detail?.id); try { const data = await apiRequest(`${API}/projects${editing ? `/${selected.detail.id}` : ''}`, { method: editing ? 'PUT' : 'POST', audience: 'admin', body }); await alerts.success(editing ? 'Project updated' : 'Project added', data.message); setSelected(null); await Promise.all([loadStats(), loadRows('projects')]); } catch (e) { setError(e.message); await alerts.error(e.message); } }); }
  async function removeProject(row) { if (!window.confirm(`Delete project “${row.project_name}”?`)) return; try { const data = await apiRequest(`${API}/projects/${row.id}`, { method: 'DELETE', audience: 'admin' }); await alerts.success('Project deleted', data.message); await Promise.all([loadStats(), loadRows('projects')]); } catch (e) { setError(e.message); } }

  return <main className="react-public-service"><header className="react-public-header"><strong>NationX Admin · Water</strong><nav><a href="/reports.html">Admin dashboard</a><button onClick={() => { clearAdminSession(); navigate('/index.html#admin'); }}>Log out</button></nav></header><section className="react-public-content"><header className="react-page-header"><div><h1>Water administration</h1><p>Connections, administrative bill review, quality, complaints and projects.</p></div></header><div className="react-service-tabs">{SECTIONS.map(value => <button className={value === section ? 'active' : ''} onClick={() => choose(value)} key={value}>{value}</button>)}</div>{error && <div role="alert" className="react-dashboard-error">{error}<button onClick={load}>Retry</button></div>}
    {section === 'dashboard' ? <div className="react-service-stats">{Object.entries(stats).map(([key, value]) => <article className="react-panel" key={key}><strong>{value || 0}</strong><span>{key.replaceAll('_', ' ')}</span></article>)}</div> : <><section className="react-panel">{section !== 'projects' && <form className="react-inline-form" onSubmit={filter}><select aria-label="Filter status" value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option>{config.statuses.map(s => <option key={s}>{s}</option>)}</select>{config.extraFilter && <select aria-label={`Filter ${config.extraFilter[0]}`} value={filters[config.extraFilter[0]]} onChange={e => setFilters({ ...filters, [config.extraFilter[0]]: e.target.value })}><option value="">All {config.extraFilter[0]}</option>{config.extraFilter[1].map(s => <option key={s}>{s}</option>)}</select>}<input aria-label="Search water admin records" value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value })} /><button>Apply filters</button></form>}</section><section className="react-panel react-service-spaced"><div className="react-section-heading"><div><h2>{section}</h2><p>{rows.length} records · page {current} of {pages}</p></div>{section === 'projects' && <button onClick={() => setSelected({ project: true, detail: {}, loading: false })}>Add project</button>}</div>{loading ? <p className="react-empty-state">Loading {section}…</p> : <><div className="react-table-wrap"><table><thead><tr><th>ID</th><th>Record</th><th>Status</th><th>Date/location</th><th>Action</th></tr></thead><tbody>{visible.map(row => <tr key={row.id}><td>{row.id}</td><td>{title(row)}</td><td><StatusBadge value={section === 'projects' ? row.status : row.status} /></td><td>{section === 'projects' ? row.division : dateText(row.created_at)}</td><td>{section === 'projects' ? <><button onClick={() => editProject(row)}>Edit</button> <button onClick={() => removeProject(row)}>Delete</button></> : <button onClick={() => view(row)}>Review</button>}</td></tr>)}{!visible.length && <EmptyRow columns={5}>No matching records.</EmptyRow>}</tbody></table></div><div className="react-pagination"><button disabled={current <= 1} onClick={() => changePage(current - 1)}>Previous</button><span>{current} / {pages}</span><button disabled={current >= pages} onClick={() => changePage(current + 1)}>Next</button></div></>}</section></>}
    {selected && !selected.project && <section className="react-panel react-service-spaced"><h2>Review {title(selected.row)}</h2>{selected.loading ? <p>Loading selected record…</p> : <><dl className="react-detail-grid">{Object.entries(selected.detail).filter(([, value]) => value !== null && typeof value !== 'object').map(([key, value]) => <div key={key}><dt>{key.replaceAll('_', ' ')}</dt><dd>{String(value)}</dd></div>)}</dl>{config.payment && <p className="react-payment-warning">Administrative demo status only — changing this field is not gateway verification.</p>}<form className="react-form-stack" onSubmit={update}><label>Status<select name="status" defaultValue={selected.detail.status}>{config.statuses.map(s => <option key={s}>{s}</option>)}</select></label>{config.fields.map(([name, label, type]) => <label key={name}>{label}{type === 'textarea' ? <textarea name={name} defaultValue={selected.detail[name] || ''} /> : <input name={name} type={type || 'text'} defaultValue={selected.detail[name] || ''} />}</label>)}<button disabled={submitting}>Update selected record</button></form></>}</section>}
    {selected?.project && <section className="react-panel react-service-spaced"><h2>{selected.detail?.id ? 'Edit project' : 'Add project'}</h2>{!selected.loading && <form className="react-form-grid" onSubmit={saveProject}>{PROJECT_FIELDS.map(([name, label, type, required]) => <label key={name}>{label}{type === 'textarea' ? <textarea name={name} defaultValue={selected.detail?.[name] || ''} /> : type === 'type' ? <select name={name} defaultValue={selected.detail?.[name] || PROJECT_TYPES[0]}>{PROJECT_TYPES.map(v => <option key={v}>{v}</option>)}</select> : type === 'status' ? <select name={name} defaultValue={selected.detail?.[name] || 'Planned'}>{PROJECT_STATUSES.map(v => <option key={v}>{v}</option>)}</select> : <input name={name} required={required} type={type || 'text'} defaultValue={selected.detail?.[name] ? String(selected.detail[name]).slice(0, type === 'date' ? 10 : undefined) : ''} />}</label>)}<label>Active<select name="is_active" defaultValue={selected.detail?.is_active === 0 ? '0' : '1'}><option value="1">Active</option><option value="0">Inactive</option></select></label><button disabled={submitting}>{selected.detail?.id ? 'Save selected project' : 'Add project'}</button></form>}</section>}
  </section></main>;
}
