import { useEffect, useRef, useState } from 'react';
import { apiRequest } from '../../services/api.js';
import ApplicantDocuments from './ApplicantDocuments.jsx';
const root='/api/nid/first-time-admin';
export default function ApplicantAdmin() {
  const [data,setData]=useState({rows:[],total:0});const [page,setPage]=useState(1);const [selected,setSelected]=useState(null);const [status,setStatus]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const pending = useRef(false);
  const load=()=>apiRequest(`${root}?page=${page}`,{audience:'admin'}).then(value => { if (!Array.isArray(value?.rows)) throw new Error('Applicant records could not be loaded. Please retry.'); setData(value); }).catch(e=>setError(e.data?.message||e.message));
  useEffect(()=>{load();},[page]);
  async function view(id){setError('');try{const row=await apiRequest(`${root}/${id}`,{audience:'admin'});setSelected(row);setStatus(row.allowed_statuses[0]||'');}catch(e){setError(e.message);}}
  async function update(event){event.preventDefault();if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await apiRequest(`${root}/${selected.id}/status`,{audience:'admin',method:'POST',body:{version:selected.version,status,remarks:new FormData(event.currentTarget).get('remarks')}});await view(selected.id);await load();}catch(e){setError(e.data?.message||e.message);}finally{pending.current=false;setBusy(false);}}
  return <section className="react-panel"><h2>First-time applicant review · NationX demo</h2><p>Separate applicant accounts. Approval does not issue an NID or activate citizen services.</p>{error&&<p role="alert">{error}</p>}<div className="react-table-wrap"><table><thead><tr><th>Tracking</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id}><td>{row.tracking_number}</td><td>{row.status}</td><td><button onClick={()=>view(row.id)}>Review applicant</button></td></tr>)}</tbody></table>{!data.rows.length&&<p>No submitted first-time applications.</p>}</div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous applicants</button><span> Page {page} </span><button disabled={page*20>=data.total} onClick={()=>setPage(p=>p+1)}>Next applicants</button>{selected&&<section><h3>{selected.tracking_number}</h3><dl>{Object.entries(selected.fields).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><ApplicantDocuments application={selected} /><ol>{selected.history.map((r,i)=><li key={i}>{r.to_status}: {r.remarks}</li>)}</ol>{selected.allowed_statuses.length>0&&<form className="react-form-stack" onSubmit={update}><label>Next applicant status<select value={status} onChange={e=>setStatus(e.target.value)}>{selected.allowed_statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Review remarks / appointment instructions<textarea name="remarks" maxLength={1000} required /></label><button disabled={busy}>Update selected applicant</button></form>}<button onClick={()=>setSelected(null)}>Close applicant</button></section>}</section>;
}
