CREATE TABLE IF NOT EXISTS land_mutations_v2 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    division_id INT,
    district_id INT,
    upazila_id INT,
    applicant_name VARCHAR(255),
    applicant_father VARCHAR(255),
    applicant_mother VARCHAR(255),
    applicant_nid VARCHAR(50),
    khatian_no VARCHAR(50),
    dag_no VARCHAR(50),
    land_amount DECIMAL(10, 2),
    land_price DECIMAL(15, 2),
    deed_no VARCHAR(100),
    ownership_type VARCHAR(50),
    buyer_name VARCHAR(255),
    buyer_nid VARCHAR(50),
    buyer_father_name VARCHAR(255),
    buyer_mother_name VARCHAR(255),
    tracking_number VARCHAR(50) UNIQUE,
    status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES reg_info(id)
);
